---
# params openssh-client

- name: Configfile openssh-client
  template:
    src: ssh_config.j2
    dest: "{{ ssh_config }}"
    owner: "{{ sshd_config_owner }}"
    group: "{{ sshd_config_group }}"
    mode: 0600
